# Generated by Django 5.2.1 on 2025-05-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_child',
            field=models.BooleanField(default=False, verbose_name='Есть дети'),
        ),
    ]
