# Generated by Django 5.2.1 on 2025-05-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_client_has_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
    ]
