# Generated by Django 5.2.1 on 2025-05-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_roomcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='comfort_type',
        ),
    ]
