# Generated by Django 5.2.1 on 2025-05-27 21:41

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_roomcategory_comfort_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[main.models.validate_age], verbose_name='Дата рождения'),
        ),
    ]
