# Generated by Django 5.2.1 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_client_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomcategory',
            name='price_per_night',
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Цена за ночь'),
            preserve_default=False,
        ),
    ]
