# Generated by Django 5.2.1 on 2025-09-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_client_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinfo',
            options={'verbose_name': 'Company info', 'verbose_name_plural': 'Company info'},
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, help_text='New line - new event. FORMAT[year: description]', verbose_name='Company History'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='YouTube link'),
        ),
    ]
