# Generated by Django 5.2.1 on 2025-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_companyinfo_options_companyinfo_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4, WebM, OGG', null=True, upload_to='company/videos/', verbose_name='VideoFile'),
        ),
    ]
