# Generated by Django 5.2.1 on 2025-09-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_companyinfo_video_url_companyinfo_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, help_text='Format: 1.0, 1.1, 2.0', max_digits=3, verbose_name='Policy version')),
                ('title', models.CharField(default='Privacy policy', max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active version')),
                ('effective_date', models.DateField(verbose_name='Date of charge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'ordering': ['-version'],
            },
        ),
    ]
