# Generated by Django 5.2.1 on 2025-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_privacypolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/', verbose_name='Logo')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Company link')),
            ],
            options={
                'verbose_name': 'Company partners',
                'verbose_name_plural': 'Company partners',
            },
        ),
    ]
