# Generated by Django 5.2.1 on 2025-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_companypartners'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypartners',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
